/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmLogin.java
 *
 * Created on Jun 2, 2009, 10:24:59 PM
 */

package gui;

import entity.Remember;
import interact.Configs;
import interact.DataInteraction;
import interact.Login;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Bach Ngoc  Toan
 */
public class frmLogin extends javax.swing.JFrame {

    /** Creates new form frmLogin */
    public frmLogin() throws ClassNotFoundException, SQLException, UnsupportedLookAndFeelException {
          Configs.loadConfigurations();
        if(!DataInteraction.connect(Configs.getProperty(Configs.CONFIG_SERVERNAME),
                Configs.getProperty(Configs.CONFIG_PORTNUMBER),
                Configs.getProperty(Configs.CONFIG_SERVERUSERNAME),
                Configs.getProperty(Configs.CONFIG_SERVERPASSWORD),
                Configs.getProperty(Configs.CONFIG_DATABASENAME))) {
            JOptionPane.showMessageDialog(null, "Cannot connect to server");
        }
        initComponents();
        //Look and feel
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Load data
         interact.GUIInteraction.readToCombo("select * from Roles", cboPermission,"RoleName");
        try {
            ObjectInputStream fis = new ObjectInputStream(new FileInputStream("info.dat"));
            entity.Remember re=(Remember) fis.readObject();
            ResultSet rsper=DataInteraction.queryResultSet("select RoleName from Roles where RoleID='"+re.getPermit()+"'");
            String role = null;
            while(rsper.next())
                role=rsper.getString("RoleName");
            txtUsername.setText(re.getUsername());
            txtPassword.setText(re.getPassword());
            cboPermission.setSelectedItem(role);
            chkRemember.setSelected(re.isCheck());
        } catch (IOException ex) {
            Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        cboPermission = new javax.swing.JComboBox();
        chkRemember = new javax.swing.JCheckBox();
        btnLogon = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login system");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login System");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .add(jLabel1)
                .add(181, 181, 181))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        lblStatus.setText("Please enter username and password to logon!!!");

        jLabel2.setText("Username:");

        jLabel3.setText("Password:");

        jLabel4.setText("Permission:");

        chkRemember.setText("Remember your password");

        btnLogon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login_1.png"))); // NOI18N
        btnLogon.setMnemonic('L');
        btnLogon.setText("Logon");
        btnLogon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogonActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logout_1.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(127, 127, 127)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblStatus))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel4)
                            .add(jLabel3)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(btnLogon)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                                .add(btnExit))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txtUsername, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, cboPermission, 0, 160, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txtPassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, chkRemember))
                        .add(16, 16, 16)))
                .add(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(lblStatus)
                .add(24, 24, 24)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtUsername, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(15, 15, 15)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(txtPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cboPermission, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .add(15, 15, 15)
                .add(chkRemember)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnLogon)
                    .add(btnExit))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogonActionPerformed
        try {
            if (!check()) {
                return;
            }
            String user = txtUsername.getText();
            char[] strpass = txtPassword.getPassword();
            String pass = new String(strpass);
            String permit = String.valueOf(cboPermission.getSelectedItem());
            //get role id
            ResultSet rsper=DataInteraction.queryResultSet("select RoleID from Roles where RoleName='"+permit+"'");
            String id = null;
            while(rsper.next())
                id=rsper.getString("RoleID");

            String sql = "select * from Administrators where Username='" + user + "' and Password='" + pass + "' and RoleID='"+id+"'";
            ResultSet rs = DataInteraction.queryResultSet(sql);
            if (rs.next()) {
                //end
                interact.Login.setAdminID(rs.getString("AdminID"));
                interact.Login.setUsername(user);
                interact.Login.setPassword(pass);
                interact.Login.setPermit(id);
                if(chkRemember.isSelected()==true) {
                    try {
                        ObjectOutputStream fos = new ObjectOutputStream(new FileOutputStream("info.dat"));
                        entity.Remember r=new Remember(Login.getUsername(),Login.getPassword(),Login.getPermit(),true);
                        fos.writeObject(r);
                    } catch (Exception ex) {
                        Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    try {
                        ObjectOutputStream fos = new ObjectOutputStream(new FileOutputStream("info.dat"));
                        entity.Remember r=new Remember("","","AD",false);
                        fos.writeObject(r);
                    } catch (Exception ex) {
                        Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                this.dispose();
                frmMain main=new frmMain();
                main.setVisible(true);
            } else
                lblStatus.setText("Login fail!Try again later!");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }catch (SQLException ex) {
            Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }catch(UnsupportedLookAndFeelException ex){
            Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_btnLogonActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
}//GEN-LAST:event_btnExitActionPerformed
private boolean check()
{
    if(!interact.CheckForm.isPwdUsername(txtUsername.getText()))
    {
        lblStatus.setText("Username invalid.");
        txtUsername.requestFocus();
        return false;
    }
    if(!interact.CheckForm.isPwdUsername(txtPassword.getText()))
    {
        lblStatus.setText("Password invalid.");
        txtPassword.requestFocus();
        return false;
    }
    return true;
}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
    try {
                new frmLogin().setVisible(true);
    } catch (ClassNotFoundException ex) {
    Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
    Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
    }catch(UnsupportedLookAndFeelException ex){
        Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE,null,ex);
    }

    }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogon;
    private javax.swing.JComboBox cboPermission;
    private javax.swing.JCheckBox chkRemember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
