/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmMain.java
 *
 * Created on May 14, 2009, 10:45:11 PM
 */

package gui;

import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import interact.*;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Bach Ngoc  Toan
 */
public class frmMain extends javax.swing.JFrame {
    /** Creates new form frmMain */
    public frmMain() throws ClassNotFoundException, SQLException, UnsupportedLookAndFeelException {
        /*Configs.loadConfigurations();
        if(!DataInteraction.connect(Configs.getProperty(Configs.CONFIG_SERVERNAME),
        Configs.getProperty(Configs.CONFIG_PORTNUMBER),
        Configs.getProperty(Configs.CONFIG_SERVERUSERNAME),
        Configs.getProperty(Configs.CONFIG_SERVERPASSWORD),
        Configs.getProperty(Configs.CONFIG_DATABASENAME))) {
        JOptionPane.showMessageDialog(null, "Cannot connect to server");
        }*/
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        try {
    setIconImage(Toolkit.getDefaultToolkit().getImage(new File("src//images//iDisk.PNG").getCanonicalPath()));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        
        permissing();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtContent = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        mnubarMain = new javax.swing.JMenuBar();
        mnuSystem = new javax.swing.JMenu();
        mniLogon = new javax.swing.JMenuItem();
        mniChangePassword = new javax.swing.JMenuItem();
        mniLogout = new javax.swing.JMenuItem();
        mniExit = new javax.swing.JMenuItem();
        mnuAdmin = new javax.swing.JMenu();
        mniUser = new javax.swing.JMenuItem();
        mniItems = new javax.swing.JMenuItem();
        mniSearchItems = new javax.swing.JMenuItem();
        mnuSalesManager = new javax.swing.JMenu();
        mniViewReport = new javax.swing.JMenuItem();
        mnuInventoryManager = new javax.swing.JMenu();
        mniCheckStatus = new javax.swing.JMenuItem();
        mnuSales = new javax.swing.JMenu();
        mniProceBilll = new javax.swing.JMenuItem();
        mniSearchItem = new javax.swing.JMenuItem();
        mniCustomer = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mniSupport = new javax.swing.JMenuItem();
        mniAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventory Manager System");

        dtContent.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannermain.jpg"))); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("About"));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Symbol-Delete.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 12));
        jLabel2.setText("© 2009 by GROUP1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Inventory Management 1.0");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel4.setText("Bach Ngoc Toan");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("GROUP1");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel6.setText("Nguyen Van Khoi");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel7.setText("Luong Hoang Manh");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel8.setText("Lam Thi Phuong Loan");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel9.setText("Thanks faculty:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel10.setText("Lai Duc Chung");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel12.setText("Contact us:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel13.setText("Y!M: cherish_snow_ngoctoan");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel14.setText("Skype: cherish_snow_ngoctoan");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel15.setText("Email:ngoctoan89@gmail.com");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel16.setText("Mobile: +84974234388");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jLabel2))
                    .add(jLabel3)
                    .add(jLabel5)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel6)
                            .add(jLabel4)
                            .add(jLabel7)
                            .add(jLabel8)))
                    .add(jLabel9)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jLabel10))
                    .add(jLabel12)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel13)
                            .add(jLabel14)
                            .add(jLabel15)
                            .add(jLabel16)))))
            .add(jPanel2Layout.createSequentialGroup()
                .add(46, 46, 46)
                .add(btnExit))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .add(18, 18, 18)
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel7)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel8)
                .add(18, 18, 18)
                .add(jLabel9)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel10)
                .add(18, 18, 18)
                .add(jLabel12)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel13)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel14)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel15)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel16)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 38, Short.MAX_VALUE)
                .add(btnExit)
                .addContainerGap())
        );

        mnuSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/System.JPG"))); // NOI18N
        mnuSystem.setText("System");
        mnuSystem.setFont(new java.awt.Font("Times New Roman", 0, 12));

        mniLogon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mniLogon.setFont(new java.awt.Font("Times New Roman", 0, 12));
        mniLogon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login_1.png"))); // NOI18N
        mniLogon.setText("Log on");
        mniLogon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLogonActionPerformed(evt);
            }
        });
        mnuSystem.add(mniLogon);

        mniChangePassword.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mniChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/repair.jpg"))); // NOI18N
        mniChangePassword.setText("Change your password");
        mniChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniChangePasswordActionPerformed(evt);
            }
        });
        mnuSystem.add(mniChangePassword);

        mniLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mniLogout.setFont(new java.awt.Font("Times New Roman", 0, 12));
        mniLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logout_1.png"))); // NOI18N
        mniLogout.setText("Log out");
        mniLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLogoutActionPerformed(evt);
            }
        });
        mnuSystem.add(mniLogout);

        mniExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mniExit.setFont(new java.awt.Font("Times New Roman", 0, 12));
        mniExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error.gif"))); // NOI18N
        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuSystem.add(mniExit);

        mnubarMain.add(mnuSystem);

        mnuAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/than.gif"))); // NOI18N
        mnuAdmin.setText("Administrators");
        mnuAdmin.setFont(new java.awt.Font("Times New Roman", 0, 12));

        mniUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniUser.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mniUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.gif"))); // NOI18N
        mniUser.setText("Add user");
        mniUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUserActionPerformed(evt);
            }
        });
        mnuAdmin.add(mniUser);

        mniItems.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniItems.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mniItems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dangki_2.gif"))); // NOI18N
        mniItems.setText("Add items/categories");
        mniItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniItemsActionPerformed(evt);
            }
        });
        mnuAdmin.add(mniItems);

        mniSearchItems.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mniSearchItems.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mniSearchItems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.gif"))); // NOI18N
        mniSearchItems.setText("Search Items");
        mniSearchItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSearchItemsActionPerformed(evt);
            }
        });
        mnuAdmin.add(mniSearchItems);

        mnubarMain.add(mnuAdmin);

        mnuSalesManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search.PNG"))); // NOI18N
        mnuSalesManager.setText("Sales Manager");
        mnuSalesManager.setFont(new java.awt.Font("Times New Roman", 0, 12));

        mniViewReport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniViewReport.setFont(new java.awt.Font("Times New Roman", 0, 12));
        mniViewReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/13.JPG"))); // NOI18N
        mniViewReport.setText("View report");
        mniViewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewReportActionPerformed(evt);
            }
        });
        mnuSalesManager.add(mniViewReport);

        mnubarMain.add(mnuSalesManager);

        mnuInventoryManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doctor_assistant-32.png"))); // NOI18N
        mnuInventoryManager.setText("Inventory Manager");
        mnuInventoryManager.setFont(new java.awt.Font("Times New Roman", 0, 12));

        mniCheckStatus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniCheckStatus.setFont(new java.awt.Font("Times New Roman", 0, 12));
        mniCheckStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Options.jpg"))); // NOI18N
        mniCheckStatus.setText("Check statistics");
        mniCheckStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCheckStatusActionPerformed(evt);
            }
        });
        mnuInventoryManager.add(mniCheckStatus);

        mnubarMain.add(mnuInventoryManager);

        mnuSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addnewMemberr.gif"))); // NOI18N
        mnuSales.setText("Sales");
        mnuSales.setFont(new java.awt.Font("Times New Roman", 0, 12));

        mniProceBilll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniProceBilll.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mniProceBilll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small_admin_icon.gif"))); // NOI18N
        mniProceBilll.setText("Produce bill");
        mniProceBilll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniProceBilllActionPerformed(evt);
            }
        });
        mnuSales.add(mniProceBilll);

        mniSearchItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniSearchItem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mniSearchItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.gif"))); // NOI18N
        mniSearchItem.setText("Search items");
        mniSearchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSearchItemActionPerformed(evt);
            }
        });
        mnuSales.add(mniSearchItem);

        mniCustomer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mniCustomer.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mniCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MemberList.gif"))); // NOI18N
        mniCustomer.setText("Customers");
        mniCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCustomerActionPerformed(evt);
            }
        });
        mnuSales.add(mniCustomer);

        mnubarMain.add(mnuSales);

        mnuHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Symbol-Help.png"))); // NOI18N
        mnuHelp.setText("Help");
        mnuHelp.setFont(new java.awt.Font("Times New Roman", 0, 12));

        mniSupport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mniSupport.setFont(new java.awt.Font("Times New Roman", 0, 12));
        mniSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista-Shield.png"))); // NOI18N
        mniSupport.setText("Get support");
        mniSupport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSupportActionPerformed(evt);
            }
        });
        mnuHelp.add(mniSupport);

        mniAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        mniAbout.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        mniAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.jpg"))); // NOI18N
        mniAbout.setText("About");
        mniAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mniAbout);

        mnubarMain.add(mnuHelp);

        setJMenuBar(mnubarMain);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dtContent, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                .addContainerGap())
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(dtContent, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCustomerActionPerformed
       frmCustomers user=new frmCustomers();
       dtContent.add(user);
       user.show();
    }//GEN-LAST:event_mniCustomerActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        int i=JOptionPane.showConfirmDialog(this,"Do you want exit system?.");
        if(i==JOptionPane.YES_OPTION)
        System.exit(1);
        
    }//GEN-LAST:event_mniExitActionPerformed

    private void mniItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniItemsActionPerformed
        frmItems it=new frmItems();
        dtContent.add(it);
        it.show();
    }//GEN-LAST:event_mniItemsActionPerformed

    private void mniSearchItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSearchItemsActionPerformed
        frmSearchItems searchItem=new frmSearchItems();
        dtContent.add(searchItem);
        searchItem.show();
    }//GEN-LAST:event_mniSearchItemsActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       System.exit(0);
}//GEN-LAST:event_btnExitActionPerformed

    private void mniProceBilllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniProceBilllActionPerformed
        frmProduceBill bill=new frmProduceBill();
        dtContent.add(bill);
        bill.show();
    }//GEN-LAST:event_mniProceBilllActionPerformed

    private void mniUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUserActionPerformed
        frmAdmin user =new frmAdmin();
        dtContent.add(user);
        user.show();
    }//GEN-LAST:event_mniUserActionPerformed

    private void mniLogonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLogonActionPerformed
        try {
            frmLogin logon = new frmLogin();
            dtContent.add(logon);
            logon.show();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }  catch(UnsupportedLookAndFeelException ex)
        {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mniLogonActionPerformed

    private void mniSearchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSearchItemActionPerformed
      frmSearchItems searchItem=new frmSearchItems();
      dtContent.add(searchItem);
      searchItem.show();
    }//GEN-LAST:event_mniSearchItemActionPerformed

private void mniChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniChangePasswordActionPerformed
    frmChangePassword change=new frmChangePassword();
    dtContent.add(change);
    change.show();
}//GEN-LAST:event_mniChangePasswordActionPerformed

private void mniLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLogoutActionPerformed
        try {
            this.dispose();
            frmLogin log = new frmLogin();
            log.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }catch(UnsupportedLookAndFeelException ex)
        {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_mniLogoutActionPerformed

private void mniAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAboutActionPerformed
  frmAbout about=new frmAbout();
  dtContent.add(about);
  about.show();
}//GEN-LAST:event_mniAboutActionPerformed

private void mniSupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSupportActionPerformed
        try {
            /*HelpManger help=new HelpManger();
            help.setVisible(true);*/
            Runtime.getRuntime().exec("rundll32.exe url.dll,FileProtocolHandler readme.html");
        } catch (IOException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_mniSupportActionPerformed

private void mniViewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniViewReportActionPerformed
    frmSalesManager sales=new frmSalesManager();
    dtContent.add(sales);
    sales.show();
}//GEN-LAST:event_mniViewReportActionPerformed

private void mniCheckStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCheckStatusActionPerformed
    frmInventoryManager invent=new frmInventoryManager();
    dtContent.add(invent);
    invent.show();
}//GEN-LAST:event_mniCheckStatusActionPerformed
//permission
    public void permissing() throws ClassNotFoundException, SQLException, UnsupportedLookAndFeelException
    {
        if(Login.getAdminID()==null&&Login.getUsername()==null&&Login.getPassword()==null&&Login.getPermit()==null)
        {
            mnuSystem.setVisible(true);
            mnuAdmin.setVisible(false);
            mnuSalesManager.setVisible(false);
            mnuInventoryManager.setVisible(false);
            mnuSales.setVisible(false);
            mnuHelp.setVisible(true);
            frmLogin login=new frmLogin();
            this.dispose();
            login.setVisible(true);
            mniChangePassword.setEnabled(false);
            mniLogout.setEnabled(false);
            
        }
        else if(Login.getPermit().equals("AD"))
        {
             mnuSystem.setVisible(true);
            mnuAdmin.setVisible(true);
            mnuSalesManager.setVisible(true);
            mnuInventoryManager.setVisible(true);
            mnuSales.setVisible(true);
            mnuHelp.setVisible(true);
            mniLogon.setEnabled(false);

        }else if(Login.getPermit().equals("SM"))
        {
            mnuSystem.setVisible(true);
            mnuAdmin.setVisible(false);
            mnuSalesManager.setVisible(true);
            mnuInventoryManager.setVisible(false);
            mnuSales.setVisible(false);
            mnuHelp.setVisible(true);
            mniLogon.setEnabled(false);
        }else if(Login.getPermit().equals("IM"))
        {
            mnuSystem.setVisible(true);
            mnuAdmin.setVisible(false);
            mnuSalesManager.setVisible(false);
            mnuInventoryManager.setVisible(true);
            mnuSales.setVisible(false);
            mnuHelp.setVisible(true);
            mniLogon.setEnabled(false);
        }
        else{
            mnuSystem.setVisible(true);
            mnuAdmin.setVisible(false);
            mnuSalesManager.setVisible(false);
            mnuInventoryManager.setVisible(false);
            mnuSales.setVisible(true);
            mnuHelp.setVisible(true);
            mniLogon.setEnabled(false);
        }

    }
private void AddForm(JInternalFrame wnd){
boolean isExist=false;
try {
for (JInternalFrame frm : dtContent.getAllFrames())
{
if(wnd.getTitle().equals(frm.getTitle()))
{
isExist=true;
break;
}
}
if(isExist==true){
dtContent.setSelectedFrame(wnd);
wnd.setSelected(true);
}
else{
dtContent.add(wnd);
wnd.setMaximum(true);
wnd.setVisible(true);
}
}
catch (Exception ex) {
ex.printStackTrace();
}
}
    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
    try {
    new frmMain().setVisible(true);
    } catch (ClassNotFoundException ex) {
    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JDesktopPane dtContent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem mniAbout;
    private javax.swing.JMenuItem mniChangePassword;
    private javax.swing.JMenuItem mniCheckStatus;
    private javax.swing.JMenuItem mniCustomer;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniItems;
    private javax.swing.JMenuItem mniLogon;
    private javax.swing.JMenuItem mniLogout;
    private javax.swing.JMenuItem mniProceBilll;
    private javax.swing.JMenuItem mniSearchItem;
    private javax.swing.JMenuItem mniSearchItems;
    private javax.swing.JMenuItem mniSupport;
    private javax.swing.JMenuItem mniUser;
    private javax.swing.JMenuItem mniViewReport;
    private javax.swing.JMenu mnuAdmin;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuInventoryManager;
    private javax.swing.JMenu mnuSales;
    private javax.swing.JMenu mnuSalesManager;
    private javax.swing.JMenu mnuSystem;
    private javax.swing.JMenuBar mnubarMain;
    // End of variables declaration//GEN-END:variables

}
