/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmProduceBill.java
 *
 * Created on May 20, 2009, 11:15:56 PM
 */

package gui;

import entity.Bill;
import interact.DataInteraction;
import interact.GUIInteraction;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Bach Ngoc  Toan
 */
public class frmProduceBill extends javax.swing.JInternalFrame {
    private boolean saleBill;
    private ArrayList<entity.BillDetail> alDetails;
    static String code=null;
    /** Creates new form frmProduceBill */
    public frmProduceBill() {
        initComponents();
        alDetails = new ArrayList<entity.BillDetail>();
        txtDiscount.setText("0");
        txtVAT.setText("1");
        refreshBills();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabBills = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        txtDiscount = new javax.swing.JTextField();
        txtVAT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboPayment = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBill = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            }
        };
        tblBill.getTableHeader().setReorderingAllowed(false);
        jLabel6 = new javax.swing.JLabel();
        txtItemID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        btnBrowerItem = new javax.swing.JButton();
        btnBrowerCustomer = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        tabDetails = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCustomerID_detail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnDetroy = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnDeleteBills = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cboOrder = new javax.swing.JComboBox();
        btnBrowerCustomerDetail = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBills2 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            }
        };
        tblBills2.getTableHeader().setReorderingAllowed(false);
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBillDetails = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            }
        };
        tblBillDetails.getTableHeader().setReorderingAllowed(false);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Bills");
        setPreferredSize(new java.awt.Dimension(810, 427));

        jLabel1.setText("Customer ID:");

        jLabel2.setText("Discount(%):");

        jLabel3.setText("VAT:");

        jLabel4.setText("Payment:");

        cboPayment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Choosing payment---", "Cash", "Credit Card", "Visa" }));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Bill Details"));

        tblBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblBill);

        jLabel6.setText("Item ID:");

        jLabel7.setText("Quantity:");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        lblTotal.setText("Total:0$");

        btnBrowerItem.setText("Brower");
        btnBrowerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowerItemActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(btnCreate)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 568, Short.MAX_VALUE)
                .add(lblTotal)
                .add(79, 79, 79))
            .add(jPanel1Layout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jLabel6)
                .add(18, 18, 18)
                .add(txtItemID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 117, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(1, 1, 1)
                .add(btnBrowerItem)
                .add(62, 62, 62)
                .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(txtQuantity, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btnAdd)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btnDelete)
                .addContainerGap(132, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(txtItemID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnBrowerItem)
                    .add(btnDelete)
                    .add(btnAdd)
                    .add(txtQuantity, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnCreate)
                    .add(lblTotal)))
        );

        btnBrowerCustomer.setText("Brower");
        btnBrowerCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowerCustomerActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout tabBillsLayout = new org.jdesktop.layout.GroupLayout(tabBills);
        tabBills.setLayout(tabBillsLayout);
        tabBillsLayout.setHorizontalGroup(
            tabBillsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tabBillsLayout.createSequentialGroup()
                .add(35, 35, 35)
                .add(tabBillsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tabBillsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(txtDiscount)
                    .add(txtCustomerID, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnBrowerCustomer)
                .add(56, 56, 56)
                .add(tabBillsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tabBillsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(txtVAT, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cboPayment, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
        );
        tabBillsLayout.setVerticalGroup(
            tabBillsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tabBillsLayout.createSequentialGroup()
                .add(38, 38, 38)
                .add(tabBillsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(txtCustomerID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3)
                    .add(txtVAT, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnBrowerCustomer))
                .add(28, 28, 28)
                .add(tabBillsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(txtDiscount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4)
                    .add(cboPayment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(19, 19, 19)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bills", new javax.swing.ImageIcon(getClass().getResource("/images/admin_member_mailier.gif")), tabBills); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter"));

        jLabel5.setText("Date from:");

        jLabel9.setText("Customer ID:");

        txtCustomerID_detail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustomerID_detailKeyReleased(evt);
            }
        });

        jLabel10.setText("Total:");

        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalKeyReleased(evt);
            }
        });

        btnDetroy.setText("Detroy");
        btnDetroy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetroyActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnDeleteBills.setText("Delete");
        btnDeleteBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBillsActionPerformed(evt);
            }
        });

        jLabel11.setText("Order by:");

        cboOrder.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Default", "Total", "Date", "Valid", "Invalid" }));
        cboOrder.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboOrderItemStateChanged(evt);
            }
        });

        btnBrowerCustomerDetail.setText("Brower");
        btnBrowerCustomerDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowerCustomerDetailActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel9)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtCustomerID_detail))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel5)
                        .add(18, 18, 18)
                        .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(btnBrowerCustomerDetail)
                        .add(29, 29, 29)
                        .add(jLabel11)
                        .add(18, 18, 18)
                        .add(cboOrder, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 194, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jLabel10)
                        .add(18, 18, 18)
                        .add(txtTotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(btnDetroy)
                        .add(18, 18, 18)
                        .add(btnRefresh)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(btnDeleteBills)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtTotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel10)
                    .add(btnDetroy)
                    .add(btnRefresh)
                    .add(btnDeleteBills))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(txtCustomerID_detail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnBrowerCustomerDetail)
                    .add(jLabel11)
                    .add(cboOrder, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Bills"));

        tblBills2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblBills2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBills2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBills2);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 736, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Bill Details"));

        tblBillDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblBillDetails);

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 734, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout tabDetailsLayout = new org.jdesktop.layout.GroupLayout(tabDetails);
        tabDetails.setLayout(tabDetailsLayout);
        tabDetailsLayout.setHorizontalGroup(
            tabDetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tabDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .add(tabDetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel4, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel3, 0, 750, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        tabDetailsLayout.setVerticalGroup(
            tabDetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tabDetailsLayout.createSequentialGroup()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Bill Details", new javax.swing.ImageIcon(getClass().getResource("/images/small_admin_icon.gif")), tabDetails); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int iQuantity=0;
        if(!interact.CheckForm.isNumberic(txtQuantity.getText()))
        {
            JOptionPane.showMessageDialog(this,"Quantity is not numberic.","Error",JOptionPane.ERROR_MESSAGE);
            txtQuantity.requestFocus();
            return;
        }
        if(Integer.valueOf(txtQuantity.getText())<0)
        {
            JOptionPane.showMessageDialog(this,"Quantity is more than zero.","Error",JOptionPane.ERROR_MESSAGE);
            txtQuantity.requestFocus();
            return;
        }
        try {
            iQuantity = Integer.valueOf(txtQuantity.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,"Fomat invalid.","Error",JOptionPane.ERROR_MESSAGE);
            txtQuantity.requestFocus();
            return;
        }
        entity.Item it=interact.Items.getByCode(txtItemID.getText());
        if(it==null)
        {
            JOptionPane.showMessageDialog(this, "This product doesn't exist","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        /*if(saleBill == true && iQuantity > it.getQuantity()) {
        JOptionPane.showMessageDialog(this, "Quantity of this item is not enough to buy");
        return;
        }*/
            boolean bFound=false;
   
            for(entity.BillDetail detail : alDetails)
            {
             if(detail.getItemID().equals(it.getItemID()))
                {
                    detail.setQuantity(detail.getQuantity()+iQuantity);
                    bFound=true;
                    break;
                }
            }
            if(bFound==false)
            {
                entity.BillDetail detail = new entity.BillDetail();
                detail.setItemID(it.getItemID());
                detail.setPrice(it.getPrice());
                detail.setQuantity(iQuantity);
                alDetails.add(detail);
            }
            refresh();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int iSelected=tblBill.getSelectedRow();
        if(iSelected<0)
        {
             JOptionPane.showMessageDialog(this, "Please choose one.");
                return;
        }
        alDetails.remove(iSelected);
        refresh();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
       //Check customerid
        boolean testCode=false;
        if(!interact.CheckForm.isEmpty(txtCustomerID.getText()))
        {
            JOptionPane.showMessageDialog(this,"You must enter customer id.");
            return;
        }
        if(!interact.CheckForm.isNumberic(txtCustomerID.getText()))
        {
            JOptionPane.showMessageDialog(this,"Customer id fomat invalid.");
            return;
        }
        int customerID = 0;
        try {
            customerID = Integer.valueOf(txtCustomerID.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,"Customer id fomat invalid.");
            return;
        }
        for(entity.Customer cus : interact.Customers.getAll())
        {
            if(cus.getCustomerID()==customerID)
            {
                testCode=true;
                break;
            }
        }
        if(testCode==false)
        {
            JOptionPane.showMessageDialog(this,"This customer id is not exist.");
            return;
        }
        //Check discount
        float disCount=0;
        try {
             disCount= Float.valueOf(txtDiscount.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,"Discount fomat invalid.");
            return;
        }
        if(disCount<0||disCount>100)
        {
            JOptionPane.showMessageDialog(this,"Discount arrange invalid.");
            return;
        }
        if(alDetails==null)
        {
            JOptionPane.showMessageDialog(this,"Please enter items.");
            return;
        }
        //check VAT
        if(!interact.CheckForm.isEmpty(txtVAT.getText()))
        {
            JOptionPane.showMessageDialog(this,"VAT is not empty.");
            return;
        }
         float vat=0;
        try {
             vat= Float.valueOf(txtVAT.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,"VAT fomat invalid.");
            return;
        }
        if(vat<0||vat>100)
        {
            JOptionPane.showMessageDialog(this,"VAT arrange invalid.");
            return;
        }
        if(cboPayment.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(this,"Please choosing payment.");
            return;
        }
         entity.Bill bill=new Bill();
         bill.setSaleID(interact.Login.getAdminID());
         bill.setDate(entity.DateUtils.now("MM/dd/yy"));
         bill.setDisCount(disCount);
         bill.setVAT(vat);
         bill.setPayment(String.valueOf(cboPayment.getSelectedItem()));
         bill.setTotal(calcTotal());
         bill.setCustomerID(customerID);
         bill.setStatus(true);
         
         try {
            interact.Bills.insertBill(bill, alDetails);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cannot create a new bill");
            return;
        }
           
            
    alDetails.clear();
    txtCustomerID.setText("");
    txtDiscount.setText("0");
    refresh();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBrowerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowerItemActionPerformed
        frmItemBrower item=new frmItemBrower();
        item.code=this;
        item.show();

    }//GEN-LAST:event_btnBrowerItemActionPerformed

    private void btnBrowerCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowerCustomerActionPerformed
          frmCustomerBrower item=new frmCustomerBrower();
        item.code=this;
        item.show();
    }//GEN-LAST:event_btnBrowerCustomerActionPerformed

    private void tblBills2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBills2MouseClicked
        int row=tblBills2.getSelectedRow();
        int billId=Integer.valueOf(tblBills2.getValueAt(row,0).toString());
        try {
            GUIInteraction.readToTable("select * from BillDetails where BillID=" + billId, tblBillDetails);
        } catch (SQLException ex) {
            Logger.getLogger(frmProduceBill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblBills2MouseClicked

    private void cboOrderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboOrderItemStateChanged
        String sql=null;
        if(cboOrder.getSelectedIndex()==0)
        {
            sql="select * from Bills where Status=1 order by BillID desc";
        }
        else if(cboOrder.getSelectedIndex()==1)
        {
            sql="select * from Bills where Status=1 order by Total desc";
        }
        else if(cboOrder.getSelectedIndex()==2)
        {
            sql="select * from Bills where Status=1 order by Date desc";
        }
        else if(cboOrder.getSelectedIndex()==3)
        {
            sql="select * from Bills where Status=1 order by BillID desc";
        }
        else
             sql="select * from Bills where Status=0 order by BillID desc";
        try {
            GUIInteraction.readToTable(sql, tblBills2);
        } catch (SQLException ex) {
            Logger.getLogger(frmProduceBill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cboOrderItemStateChanged

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refreshBills();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDeleteBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBillsActionPerformed
       
        int row=tblBills2.getSelectedRow();
       int id = Integer.valueOf(tblBills2.getValueAt(row, 0).toString());
       if(row<0)
       {
            JOptionPane.showMessageDialog(this,"You must choose a bill.");
            return;
       }
      int i= JOptionPane.showConfirmDialog(this,"Do you want to delete bill selected.");
      if(i==JOptionPane.YES_OPTION)
      {

            String sql="delete from Bills where BillID="+id;
            DataInteraction.exec(sql);
            refreshBills();
      }
    }//GEN-LAST:event_btnDeleteBillsActionPerformed

    private void btnBrowerCustomerDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowerCustomerDetailActionPerformed
         frmCustomerBrower_1 item=new frmCustomerBrower_1();
        item.code=this;
        item.show();
    }//GEN-LAST:event_btnBrowerCustomerDetailActionPerformed

    private void txtCustomerID_detailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerID_detailKeyReleased
        int cusID=1;
        try {
            cusID = Integer.valueOf(txtCustomerID_detail.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,"Invalid fomat.");
            return;
        }
        String sql="select * from Bills where Status=1 and CustomerID="+cusID;
        try {
            GUIInteraction.readToTable(sql, tblBills2);
        } catch (SQLException ex) {
            Logger.getLogger(frmProduceBill.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtCustomerID_detailKeyReleased

    private void txtTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyReleased
       float total=1;
        try {
            total = Float.valueOf(txtTotal.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,"Invalid fomat.");
            return;
        }
        String sql="select * from Bills and Status=1 where Total="+total;
        try {
            GUIInteraction.readToTable(sql, tblBills2);
        } catch (SQLException ex) {
            Logger.getLogger(frmProduceBill.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_txtTotalKeyReleased

    private void btnDetroyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetroyActionPerformed
        int row=tblBills2.getSelectedRow();
  
       if(row<0)
            {
            JOptionPane.showMessageDialog(this,"You must choose a bill.");
              return;
            }
      int i= JOptionPane.showConfirmDialog(this,"Do you want to detroy bill selected.");
      if(i==JOptionPane.YES_OPTION)
      {
       String id =tblBills2.getValueAt(row, 0).toString();
                String sql = "update Bills set Status=0 where BillID=" + id;
                DataInteraction.exec(sql);
                /*int quan = 0;
                float total = 0;
                int cusID = 0;
                ResultSet rs = DataInteraction.queryResultSet("select CustomerID,Total,Quantity from Bills,BillDetails where Bills.BillID=BillDetails.BillID and Bills.BillID=" + id);
                while (rs.next()) {
                cusID=rs.getInt("CustomerID");
                total=rs.getFloat("Total");
                quan=rs.getInt("Quantity");
                }
                String strSql="{call spDetroyBill(?,?,?,?)}";
                CallableStatement cs=DataInteraction.getConnect().prepareCall(sql);
                cs.setInt(1,quan);
                cs.setString(2, id)*/;
                refreshBills();   
      }
    }//GEN-LAST:event_btnDetroyActionPerformed
private float calcTotal() {
    float dTotal = 0;

    for(entity.BillDetail detail : alDetails) {
        dTotal += detail.getPrice() * detail.getQuantity();
    }

    double dDiscount = 0;
    try {
        dDiscount = Double.valueOf(txtDiscount.getText());
    } catch (Exception ex) {
    }
    dDiscount = Math.min(Math.max(dDiscount, 0), 100);
    dTotal *= (100 - dDiscount) / 100;
    lblTotal.setText("Total: $" + dTotal);

    return dTotal;
}
private void refresh()
{
    tblBill.setModel(new model.BillDetails(alDetails));
    calcTotal();
}
private void refreshBills()
{
        try {
            GUIInteraction.readToTable("select * from Bills where Status=1", tblBills2);
        } catch (SQLException ex) {
            Logger.getLogger(frmProduceBill.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBrowerCustomer;
    private javax.swing.JButton btnBrowerCustomerDetail;
    private javax.swing.JButton btnBrowerItem;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteBills;
    private javax.swing.JButton btnDetroy;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox cboOrder;
    private javax.swing.JComboBox cboPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel tabBills;
    private javax.swing.JPanel tabDetails;
    private javax.swing.JTable tblBill;
    private javax.swing.JTable tblBillDetails;
    private javax.swing.JTable tblBills2;
    public javax.swing.JTextField txtCustomerID;
    public javax.swing.JTextField txtCustomerID_detail;
    private javax.swing.JTextField txtDiscount;
    public javax.swing.JTextField txtItemID;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtVAT;
    // End of variables declaration//GEN-END:variables

}
