/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmSalesManager.java
 *
 * Created on May 29, 2009, 8:59:37 PM
 */

package gui;

import interact.GUIInteraction;
import java.applet.Applet;
import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.AnimatedChart;
import model.Selling;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author Bach Ngoc  Toan
 */
public class frmSalesManager extends javax.swing.JInternalFrame {

    /** Creates new form frmSalesManager */
    public frmSalesManager() {
        initComponents();
        lblToday.setText(entity.DateUtils.now("MM/dd/yyyy"));
        txtViewBills.setText(entity.DateUtils.now("MM/dd/yyyy"));
        txtMoney.setText(entity.DateUtils.now("MM/dd/yyyy"));
        txtBillsCancel.setText(entity.DateUtils.now("MM/dd/yyyy"));
        txtItemsCancel.setText(entity.DateUtils.now("MM/dd/yyyy"));
        try {
            txtItemNot.setText(String.valueOf(interact.GUIInteraction.countRecord("select * from V_Items where QuantityAvailable<=0")));
        } catch (SQLException ex) {
            Logger.getLogger(frmSalesManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtItemNot = new javax.swing.JTextField();
        btnViewItemNot = new javax.swing.JButton();
        btnViewAll = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            }
        };
        tblItems.getTableHeader().setReorderingAllowed(false);
        btnItemCanceled = new javax.swing.JButton();
        btnViewBills = new javax.swing.JButton();
        btnViewMoney = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        btnViewDetails2 = new javax.swing.JButton();
        btnViewAll1 = new javax.swing.JButton();
        btnGenerate1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItems1 = new javax.swing.JTable();
        btnViewDetails3 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnViewCanceled = new javax.swing.JButton();
        txtItemsCancel = new javax.swing.JTextField();
        txtViewBills = new javax.swing.JTextField();
        txtMoney = new javax.swing.JTextField();
        txtBillsCancel = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblToday = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Sales Manager");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Check Statistics");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(202, 202, 202)
                .add(jLabel1)
                .addContainerGap(355, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("View bills:");

        jLabel3.setText("View money transtract:");

        jLabel4.setText("Bills canceled:");

        jLabel5.setText("Items canceled:");

        jLabel6.setText("Items not available:");

        txtItemNot.setEditable(false);

        btnViewItemNot.setText("View");
        btnViewItemNot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewItemNotActionPerformed(evt);
            }
        });

        btnViewAll.setText("View All");
        btnViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllActionPerformed(evt);
            }
        });

        btnGenerate.setText("Generating graphs");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblItems);

        btnItemCanceled.setText("View");
        btnItemCanceled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemCanceledActionPerformed(evt);
            }
        });

        btnViewBills.setText("View");
        btnViewBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBillsActionPerformed(evt);
            }
        });

        btnViewMoney.setText("View");
        btnViewMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMoneyActionPerformed(evt);
            }
        });

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setTitle("Sales Manager");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 36));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Check Statistics");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(202, 202, 202)
                .add(jLabel7)
                .addContainerGap(303, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel7)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("View bills:");

        jLabel9.setText("View money transtract:");

        jLabel10.setText("Bills canceled:");

        jLabel11.setText("Items canceled:");

        jLabel12.setText("Items not available:");

        btnViewDetails2.setText("View");

        btnViewAll1.setText("View All");
        btnViewAll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAll1ActionPerformed(evt);
            }
        });

        btnGenerate1.setText("Generating graphs");

        tblItems1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblItems1);

        btnViewDetails3.setText("View");

        jButton3.setText("View");

        jButton4.setText("View");

        org.jdesktop.layout.GroupLayout jInternalFrame1Layout = new org.jdesktop.layout.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jInternalFrame1Layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel9)
                    .add(jLabel8)
                    .add(jLabel10))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jFormattedTextField7)
                    .add(jFormattedTextField6)
                    .add(jFormattedTextField5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .add(jButton3)
                                .add(13, 13, 13)
                                .add(jLabel12))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .add(jButton4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel11)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jFormattedTextField8)
                            .add(jTextField2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(btnViewDetails3)
                            .add(btnViewDetails2)))
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(100, 100, 100)
                        .add(btnViewAll1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(btnGenerate1)))
                .add(66, 66, 66))
            .add(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jInternalFrame1Layout.createSequentialGroup()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(37, 37, 37)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(jFormattedTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnViewDetails2)
                    .add(jLabel12)
                    .add(jButton3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel9)
                    .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jFormattedTextField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel11)
                        .add(jFormattedTextField8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(btnViewDetails3)
                        .add(jButton4)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jFormattedTextField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(btnGenerate1)
                        .add(btnViewAll1))
                    .add(jLabel10))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnViewCanceled.setText("View");
        btnViewCanceled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCanceledActionPerformed(evt);
            }
        });

        jLabel13.setText("MM/DD/YYYY");

        jLabel14.setText("Date fomat:");

        lblNumber.setText("Number bills:");

        jLabel15.setText("Today:");

        lblToday.setText("Today");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(jLabel4)
                    .add(jLabel14))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel13)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(txtBillsCancel)
                            .add(txtMoney)
                            .add(txtViewBills, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 21, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(btnViewBills)
                            .add(btnViewMoney)
                            .add(btnViewCanceled))
                        .add(6, 6, 6)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(40, 40, 40)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel6)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel5)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel15))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(txtItemNot, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(txtItemsCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(btnItemCanceled)
                                            .add(btnViewItemNot)))
                                    .add(lblToday)))
                            .add(layout.createSequentialGroup()
                                .add(94, 94, 94)
                                .add(btnViewAll)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(btnGenerate)))
                        .add(66, 66, 66))))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(lblNumber)
                .addContainerGap(696, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 393, Short.MAX_VALUE)
                    .add(jInternalFrame1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 393, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(jLabel14)
                    .add(jLabel15)
                    .add(lblToday))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(txtItemNot, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnViewItemNot)
                    .add(jLabel6)
                    .add(txtViewBills, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnViewBills))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(btnItemCanceled)
                    .add(txtItemsCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3)
                    .add(btnViewMoney)
                    .add(txtMoney, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnGenerate)
                    .add(btnViewAll)
                    .add(jLabel4)
                    .add(btnViewCanceled)
                    .add(txtBillsCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblNumber)
                .addContainerGap(31, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 224, Short.MAX_VALUE)
                    .add(jInternalFrame1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 225, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllActionPerformed
        try {
            GUIInteraction.readToTable("select * from V_Items", tblItems);
        } catch (SQLException ex) {
            Logger.getLogger(frmSalesManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewAllActionPerformed

    private void btnViewAll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAll1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewAll1ActionPerformed

    private void btnViewBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBillsActionPerformed
        String d=txtViewBills.getText();
        if(!interact.CheckForm.validateDate(d))
        {
            JOptionPane.showMessageDialog(this,"Date fomat invalid");
            return;
        }
        try {
            GUIInteraction.readToTable("select * from V_BillInDay where DateTranstract='"+d+"'", tblItems);
        } catch (SQLException ex) {
            Logger.getLogger(frmSalesManager.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            lblNumber.setText("Bills generated in day:"+String.valueOf(GUIInteraction.countRecord("select * from V_BillInDay where DateTranstract='" + d + "'")));
        } catch (SQLException ex) {
            Logger.getLogger(frmSalesManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewBillsActionPerformed

    private void btnViewMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMoneyActionPerformed
         String d=txtMoney.getText();
        if(!interact.CheckForm.validateDate(d))
        {
            JOptionPane.showMessageDialog(this,"Date fomat invalid");
            return;
        }
        try {
            GUIInteraction.readToTable("select sum(Total) as TotalMoney from V_BillInDay where DateTranstract='"+d+"'", tblItems);
        } catch (SQLException ex) {
            Logger.getLogger(frmSalesManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewMoneyActionPerformed

    private void btnViewCanceledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCanceledActionPerformed
       String d=txtBillsCancel.getText();
        if(!interact.CheckForm.validateDate(d))
        {
            JOptionPane.showMessageDialog(this,"Date fomat invalid");
            return;
        }
        try {
            GUIInteraction.readToTable("select * from V_BillInDay where Status=0 and DateTranstract='"+d+"'", tblItems);
        } catch (SQLException ex) {
            Logger.getLogger(frmSalesManager.class.getName()).log(Level.SEVERE, null, ex);
        }
       try {
            GUIInteraction.countRecord("select * from V_BillInDay where Status=0 and DateTranstract='"+d+"'");
        } catch (SQLException ex) {
            Logger.getLogger(frmSalesManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewCanceledActionPerformed

    private void btnViewItemNotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewItemNotActionPerformed
        try {
            interact.GUIInteraction.readToTable("select * from V_Items where QuantityAvailable<=0",tblItems);
        } catch (SQLException ex) {
            Logger.getLogger(frmSalesManager.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_btnViewItemNotActionPerformed

    private void btnItemCanceledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemCanceledActionPerformed
        String d=txtItemsCancel.getText();
        if(!interact.CheckForm.validateDate(d))
        {
            JOptionPane.showMessageDialog(this,"Date fomat invalid");
            return;
        }
        try {
            GUIInteraction.readToTable("select * from V_ItemsCancel where DateTranstract='"+d+"'", tblItems);
        } catch (SQLException ex) {
            Logger.getLogger(frmSalesManager.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_btnItemCanceledActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        /*try {
        final Selling demo = new Selling("Sales-trend graphs for each of the item");
        demo.pack();
        RefineryUtilities.centerFrameOnScreen(demo);
        demo.setVisible(true);
        } catch (SQLException ex) {
        Logger.getLogger(frmSalesManager.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        Frame frame = new Frame("Animated Chart");
    frame.addWindowListener(new WindowAdapter() {
            @Override
              public void windowClosing(WindowEvent event) {
                System.exit(0);
              }
            });
    Applet applet = new AnimatedChart();
    applet.init();
    frame.add(applet);
    frame.setSize(600, 500);
    frame.show();
    }//GEN-LAST:event_btnGenerateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnGenerate1;
    private javax.swing.JButton btnItemCanceled;
    private javax.swing.JButton btnViewAll;
    private javax.swing.JButton btnViewAll1;
    private javax.swing.JButton btnViewBills;
    private javax.swing.JButton btnViewCanceled;
    private javax.swing.JButton btnViewDetails2;
    private javax.swing.JButton btnViewDetails3;
    private javax.swing.JButton btnViewItemNot;
    private javax.swing.JButton btnViewMoney;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblToday;
    public javax.swing.JTable tblItems;
    private javax.swing.JTable tblItems1;
    private javax.swing.JTextField txtBillsCancel;
    private javax.swing.JTextField txtItemNot;
    private javax.swing.JTextField txtItemsCancel;
    private javax.swing.JTextField txtMoney;
    private javax.swing.JTextField txtViewBills;
    // End of variables declaration//GEN-END:variables

}
