/*
 * HelpManger.java
 *
 * Created on March 16, 2009, 9:27 AM
 */

package gui;

import java.awt.BorderLayout;
import java.awt.Font;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.JEditorPane;
import javax.swing.JScrollPane;
import javax.swing.JViewport;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLFrameHyperlinkEvent;

/**
 *
 * @author  Bach Ngoc Toan
 */
public class HelpManger extends javax.swing.JFrame {
    JEditorPane html;
    /// String path = null;
    public HelpManger() {
        initComponents();
        Font f = new Font("Vni-Times", Font.CENTER_BASELINE, 12);
        try { 

            String path = "file:///E:/eproject/Source/InventoryManagement2/readme.html";
           // path ="/Image/readme.html";    
            URL url = new URL(path);
            if(url != null) 
            { 
                    html = new JEditorPane(url); 
                    html.setEditable(false); 
                    html.addHyperlinkListener(createHyperLinkListener()); 

                    JScrollPane scroller = new JScrollPane(); 
                    JViewport vp = scroller.getViewport(); 
                    vp.add(html); 
                    getContentPane().setLayout(new BorderLayout());
                    getContentPane().add(scroller, BorderLayout.CENTER);
            }else
            { 
                    System.out.println("URL not found : "+url);
            }
            } catch (MalformedURLException e) { 
                    System.out.println("Malformed URL: " + e); 
            } catch (IOException e) { 
                    System.out.println("IOException: " + e); 
            }
    }
    public HyperlinkListener createHyperLinkListener() { 
        return new HyperlinkListener() {
            public void hyperlinkUpdate(HyperlinkEvent e) {
                if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
                    if (e instanceof HTMLFrameHyperlinkEvent) {
                        ((HTMLDocument) html.getDocument()).processHTMLFrameHyperlinkEvent(
                                (HTMLFrameHyperlinkEvent) e);
                    } else {
                        try {
                            html.setPage(e.getURL());
                        } catch (IOException ioe) {
                            System.out.println("IOE: " + ioe);
                        }
                    }
                }
}          
        }; 
}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventory Management System Help");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 514, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 451, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
    new HelpManger().setVisible(true);
    }
    });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
